ExploreASL/ExploreASL

- Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
> Fix registration bug & report TC instead of sCoV

- ExploreASL_Import.m
Hi Michael, I created a separate issue for you, for which you can work at a separate branch (which is essentially the same as having it locally only, only allowing you to merge easier. If you push regularly, we can review and give tips or learn ;)
What I suggest in this commit:
* shortening your code change
* keeping the primary BIDS structure (i.e. raw/derivative/etc, though we need to adapt some of this still)
* instead of crashing when there is no /raw/, it will throw a warning and try to find another folder that is not specified as other BIDS folder, and only give an error if there are multiple folders or none, similar to what you had. But it will provide a specific error (instead of continuing and crashing later).
How does this sound to you? ;)
> #32Suggested Fix Import Michael

- Functions/xASL_Iteration.m
Fixes #41, wait with closing this issue 1 week, or until the user responds in the correct channel. So the user can read the answer.
> Minorfix #41 insert warning4 incomplete initialization

- External/SPMmodified/xASL/xASL_io_Nifti2Im.m
> #48 xASL_io_Nifti2Im.m detect wrong scaling

- Functions/xASL_adm_LoadParms.m
- Functions/xASL_num2str.m
Close #67 
- Fixed the issue with overwriting arrays in xASL_adm_LoadParms
> #67 Fixed the issue with overwritting arrays in xASL_adm_LoadParms

- External/SPMmodified/xASL/xASL_SysMove.m
Tested with TestDataSet in compiled mode on windows.
> #88 SysMove error in deployed mode for windows

- Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
Fixes #93 
@MauricePasternak does this fix the issue? It was only the '=' symbol that needed removing right?
Thanks!
> #93 Fixes #93

- Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
@MauricePasternak you want to check this branch out and test if xASL_wrp_CreatePopulationTemplates now works for you?
This should fix #102
> #102 Fixes #102

- Development/xASL_qc_TestExploreASL.m
Actually this was a bug, not a feature ;)
But anyway this is a developer feature.
I have now recreated this change from the hotfix branch, so we can insert this in release 1.2.1.
Makes for easier testing ;)
I cannot assign myself as reviewer though :(
> Fixed the results table creation for TestCases

- Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
Bug seems to be fixed by df42d5c
> Fixes #118

- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
Closes #120 
Does not write temporary files to the shared template folder but only to the individual subjects folder
> #120 Fixes the native space population parallel processing

- Functions/xASL_spm_deformations.m
> Closes #145 x asl spm deformations zipping functionality

- Development/SaraElgayar_BIDS/xASL_module_Structural_SE.m
- Functions/README.md
- Functions/xASL_vis_VisualizeROIs.m
- Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
* Bug in Lesion lists fixed.
* Merged the code for T1 and FLAIR lists and simplified the code.
Close #148
> Feature #148 fixing t1 flair lists

- Modules/xASL_module_Structural.m
Ensure that FLAIR status files are also created without FLAIRs or WMHs, to avoid confusing external progress trackers
> #123 CreateMissingFLAIRStatus

- Development/StatsAnalysis/SPM_VBA_Stats/xASL_wrp_spm_GLM.m
> Closes #159 Use consistent notation

- External/SPMmodified/xASL/xASL_adm_GetFileList.m
- Functions/xASL_vis_Imwrite.m
- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
- Modules/xASL_module_Population.m
See the issue, perhaps not the nicest programming but should be fine for now
> Bug #143 masks missing

- Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
- Modules/SubModule_ASL/xASL_wrp_Quantify.m
- Modules/xASL_module_ASL.m
Rewrote the three ApplyQuantification usages as discussed in issue 85
Closes #85
> #85 Improvement ApplyQuantification

- External/TestDataSet/analysis/DataParameters_HiQ.json
- External/TestDataSet/analysis/DataParameters_LowQ.json
> #162 Remove bNativeSpaceProcessing from TestdataSet for now

- Functions/xASL_bids_Add2ParticipantsTSV.m
- Functions/xASL_stat_GetROIstatistics.m
- Functions/xASL_stat_PrintStats.m
- Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
- Modules/xASL_module_Structural.m
> Bug #105 error when no asl data

- Development/Documentation_GitHub/Functions.md
- Development/Documentation_GitHub/index.md
- Development/xASL_doc_Crawler.m
- Development/xASL_doc_Initialize.m
- Functions/README.md
- Functions/xASL_adm_SaveX.m
- Functions/xASL_bids_MergeNifti.m
- Functions/xASL_im_SplitImageLabels.m
- Minor changes to the **documentation crawler** for the **functions folder**.
- **xASL_doc_Initialize** will now create markdown files in the Documentation_GitHub folder.
- These markdown files can then be copied to the **ExploreASL/Documentation** repository into the **docs** folder.
- These could be first steps to automate the documentation generation.
- Fixed minor header issues.
These changes shouldn't require external reviewers, since we agreed that minor changes for the documentation can even be done directly in the develop branch.
> Feature #217 documentation improvements

- Development/BIDS/xASL_bids_compareStructures.m
- Functions/xASL_bids_CompareStructures.m
Closes #193 
* Compares two directories and their subdirectories.
* Reports missing files and directories in each of the paths.
* Compares content of JSON, NII, TXT, TSV and CSV files and reports differences.
> Feature #193 compare bid sfolders

- ExploreASL.m
- ExploreASL_Initialize.m
- ExploreASL_Master.m
> Closes #241 Add warning when chosen loading data without x structure output

- Functions/xASL_adm_MakeStandalone.m
- Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
- README.md
Closes #191, 1) detect native space FLAIR/WMH NIfTI, if absent, do not create NaN default, 2) Warning is now dependent on (1)
> Close #191 xASL_stat_GetVolumeStatistics: remove FLAIR warning

- DataParTemplate.m
- ExploreASL_Master.m
> Closes #225: Feature #225 option longitudinal registration

- CHANGES.md
- Functions/xASL_im_ComputeDice.m
- Functions/xASL_im_SplitImageLabels.m
- Functions/xASL_stat_PairwiseDice.m
- Functions/xASL_stat_UniquePairwisePermutations.m
- Functions/xASL_vis_CreateVisualFig.m
- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
- Modules/SubModule_Population/xASL_wrp_CreatePopulationTemplates.m
- Modules/xASL_module_Population.m
> Feature #179 cicero

- External/README_SPM.txt
- External/SPMmodified/spm_load.m
- External/SPMmodified/xASL/xASL_tsvRead.m
- External/SPMmodified/xASL/xASL_tsvWrite.m
Closes #276, I would like to make this a hotfix as well.
> #276 xASL_tsvRead fixed

- Modules/xASL_module_Population.m
Closes #282 
@MDijsselhof  Another nice one for you ;) You can also merge this one, see if that works for you! Otherwise, we can do this together the first couple of times.
> #282 xASL_module_Population: iWorker>1 error fixed

- Functions/xASL_stat_GetROIstatistics.m
> #283 xASL_stat_GetROIstatistics Improve feedback on missing images

- README.md
Minor changes: added badges for the docu link and the version number
> Closes #300 readme

- ExploreASL.m
Closes #285
(@MDijsselhof this should be a very easy one for you to start with ;)
> #285 ExploreASL: Add x=ans hint

- External/README_SPM.txt
- External/SPMmodified/spm_update.m
- External/SPMmodified/toolbox/LST/ps_LST_update.m
- External/SPMmodified/toolbox/cat12/cat12.m
- External/SPMmodified/toolbox/cat12/cat_io_send_to_server.m
- External/SPMmodified/toolbox/cat12/cat_update.m
Closes #302
(Tested this with /External/TestDataSet)
> #302 Remove SPM/LST/CAT12 server calls

- DataParTemplate.m
- Modules/xASL_module_ASL.m
Hey, I added a second line with a default for `x.M0` if `x.M0PositionInASL4D` is not empty. Is it correct like this? I couldn't find another default value in the DataParTemplate.
> Closes #272

- Modules/SubModule_Population/xASL_qc_SortBySpatialCoV.m
The solution prived by Henk-Jan works for me, so I've created a pull-request. 
@HenkMutsaerts if you can review the pull-request, I can merge it!
closes #292
> #292 xASL_qc_SortBySpatialCoV: use specific number of subjects

- Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
> #329 xASL_stat_GetVolumeStatistics: str2num -> xASL_str2num

- Functions/xASL_im_ClipExtremes.m
- Modules/SubModule_Structural/xASL_wrp_LinearReg_FLAIR2T1w.m
- Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m
- Modules/SubModule_Structural/xASL_wrp_SegmentT1w.m
> Bug #309 toohigh values

- External/TestDataSet/analysis/Sub-001/ASL_1/ASL4D.json
- External/TestDataSet/analysis/Sub-001/ASL_1/M0.json
- Functions/xASL_adm_LoadParms.m
> Closes #306 PhaseEncodingAxis

- CustomScripts/EPAD/EPAD_Manage_PEPolar_Parms.m
> #296 added M0-option for looking for Phase Encoding direction

- External/SPMmodified/xASL/xASL_delete.m
- Functions/xASL_adm_CleanUpBeforeRerun.m
> Bug #325 x asl adm clean up before rerun

- External/SPMmodified/toolbox/cat12/cat_io_report.m
- Modules/SubModule_Structural/xASL_wrp_SegmentT1w.m
> Bug #228 cat12 warnings

- External/mediri/xASL_io_mTRIAL.m
Code change in `External`, does **not** require review
> Closes #343

- Functions/xASL_bids_Add2ParticipantsTSV.m
- Functions/xASL_bids_parms2BIDS.m
Close #363 
I am responsible for error 1 - so this fix should be fine. 
But I am not responsible for error 2 - please check (Michael, Henk) if my fix makes sense or makes things worse :)
> Bug #363 release1.5.0 pre testing

- DataParTemplate.m
Only minor changes. Everything is described in #355
> Closes #355

- Development/BIDS/BIDS_fullPipelineTest.m
- Development/xASL_test_BIDSFlavorsFull.m
- Functions/xASL_bids_parms2BIDS.m
- Functions/xASL_import_json.m
- Functions/xASL_quant_SliceReadoutTime_ShortestTR.m
Fixing several bugs:
- Range checking of SliceReadoutTime as a vector wasn't working properly.
- JSON_import was not accepting logical type as valid.
- The BIDS flavors testing script needed to fix correctly the path in the legacy processing step.
Close #372
> Bug #371 flavors legacy processing

- ExploreASL_ImportBIDS.m
- Functions/xASL_bids_parms2BIDS.m
> Bug #373 parameter parsing in dicom2 bids

- Functions/xASL_adm_LoadParms.m
- Functions/xASL_import_json.m
> Bug #378 stop reading complex numbers

- DataParTemplate.m
- External/mediri/xASL_io_mTRIAL.m
- Functions/xASL_io_SplitASL.m
- Functions/xASL_io_SplitASL_M0.m
- Modules/xASL_module_ASL.m
> Feature #354 xASL_io_SplitASL_M0: Remove asl dummy

- ExploreASL_Import.m
- ExploreASL_ImportBIDS.m
> #382 Reorder CCLL to CLCL for PARREC import

- Functions/xASL_adm_ReplaceSymbols.m
> #430 xASL_adm_ReplaceSymbols: Warning not error with unknown symbols

- ExploreASL_ImportBIDS.m
- Functions/xASL_bids_MergeNifti.m
Closes #421 
Tested and worked with Flavors database.
Haven't tested the CBF option as I don't have that data.
> #421 Automatic import scan order in GE

- Functions/xASL_test_GetLogContent.m
> Close #352 Improve Log Parsing

- Functions/xASL_im_ResampleLinearFair.m
Hey @jan-petr, check out the detailed explanation in the issue #387.
> Closes #387: xASL_im_ResampleLinearFair: Waitbar bug

- Development/xASL_test_BIDSFlavorsFull.m
- ExploreASL_ImportBIDS.m
> Bids #426 GE parameters dicom

- Functions/xASL_bids_PhoenixProtocolAnalyzer.m
- Functions/xASL_bids_PhoenixProtocolReader.m
Hey @MDijsselhof, can you give this a try?
Just get a Siemens DICOM with Phoenix Protocol and run something like:
```
>> dicom = 'mytestfile.dcm';
>> [xasl,parameters,parameterList,phoenixProtocol] = xASL_bids_GetPhoenixProtocol(dicom,1);
```
> Closes #424 Phoenix Reader and Analyzer fix

- Development/BIDS/BIDS_fullPipelineTest.m
At the start of BIDS_fullPipelineTest.m we define our local folder structure like this:
``` 
%% Preparation for Jan 
if strcmp(username,'janpetr')
pathExploreASL = '/home/janpetr/ExploreASL/ExploreASL';
pathTest = '/pet/projekte/asl/data/BIDS';
cmdCloneFlavors = 'git clone git@github.com:ExploreASL/FlavorDatabase.git';
end 
```
You could add you own usernames and corresponding folder structure there.
> #383 Added custom paths to Flavors test script

- Development/BIDS/BIDS_fullPipelineTest.m
- Development/xASL_bids_TestBidsConversion.m
- Development/xASL_test_BIDSFlavorsFull.m
- Functions/xASL_bids_CompareStructures.m
- Functions/xASL_bids_Dicom2JSON.m
> Closes #416 bids full test optimization

- External/SPMmodified/xASL/xASL_Copy.m
> #415 xASL_Copy: Allow recursive copying of folders

- Development/xASL_bids_TestBidsConversion.m
- Functions/xASL_bids_CompareStructures.m
> Closes #395 xASL_bids_CompareStructures

- ExploreASL_ImportBIDS.m
- Functions/xASL_bids_CreateDatasetDescriptionTemplate.m
> #443 Fix dataset_description defaults in ImportBIDS

- DataParTemplate.json
> Bids #266 clean json data par

- DataParTemplate.m
- Functions/xASL_init_FileSystem.m
- Functions/xASL_io_ReadDataPar.m
> #452 added atlas descriptions to DataParTemplate

- Functions/xASL_io_SplitASL.m
- Modules/xASL_module_ASL.m
> #433 Enable ASL split on re-run

- Functions/xASL_quant_SliceTiming.m
> Bids #418 slice timing consistency

- Functions/xASL_init_FileSystem.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
External Vascular territories atlases paths end with incorrect file extensions and should all end with `.nii.gz`
> #477 Incorrect external atlases paths

- Functions/xASL_Iteration.m
> #156 xASL_Iteration: include module & subject in error message

- Functions/xASL_qc_CollectQC_ASL.m
- Functions/xASL_stat_ComputeMean.m
- Functions/xASL_stat_ComputeSpatialCoV.m
- Functions/xASL_stat_GetROIstatistics.m
- Modules/SubModule_Population/xASL_stat_ComputeWsCV.m
> Bug #184 low mean cbf test data

- ExploreASL_ImportBIDS.m
- External/SPMmodified/xASL/xASL_Copy.m
- External/SPMmodified/xASL/xASL_Move.m
This PR is supposed to fix issue #411.
@jan-petr: It was a bit troublesome for me to properly test the code, since we fixed the xASL SysCopy script in another branch. On windows it's a bit annoying to test the code without that change from #483. Can you run some minor tests using BIDS_fullPipelineTest on linux? In the last commit I moved some code for the NIIX2ASL-BIDS part to a subfunction. I hope this doesn't break anything.
I'm not sure if you want me to merge or if you want to do it because of possible conflicts in the import workflow.
> Closes #411 Delete analysis folder

- DataParTemplate.m
- ExploreASL_Initialize.m
Check comments and examples in #494.
Run tests shown in #494 if necessary.
Would be helpful to tell me how you want line 659 in `ExploreASL_Initialize` to look like.
> #494 ExploreASL_Initialize: Fix cross-platform settings design

- External/SPMmodified/toolbox/cat12/cat_main.m
- External/SPMmodified/xASL/xASL_SysMove.m
- External/SPMmodified/xASL/xASL_adm_UnzipNifti.m
- External/SPMmodified/xASL/xASL_io_SaveNifti.m
> #475 Fix bug with space in study folder name

- External/SuperGZip/LICENSE
- Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
- Modules/xASL_module_Population.m
Check out #262. I changed some minor things and tested it using the TestDataSet. I couldn't find any bugs.
> Closes #262 Super G-Zip Windows

- Functions/xASL_adm_DocCrawler.m
- Functions/xASL_adm_DocInitialize.m
Really minor update for the documentation of v1.6.0
Check out issue #515
> Closes #515 Documentation update v1.6.0

- External/SPMmodified/xASL/xASL_spm_admin.m
- External/SPMmodified/xASL/xASL_spm_reslice.m
- External/SPMmodified/xASL/xASL_spm_smooth.m
> Bug #502 x asl spm smooth

- Functions/xASL_bids_DRO2BIDS.m
- Testing/UnitTests/xASL_ut_UnitTest_function_BIDS2Legacy.m
> Closes #467 DRO2BIDS

- ExploreASL_Initialize.m
- ExploreASL_Master.m
Introduce a bReinitialize to the x struct to handle the reinitialization behavior
> Closes #518 Introduce bReinitialize

- ExploreASL_Import.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Initialize.m
> #505 TokenAliases allow row vectors

- Functions/xASL_io_SplitASL.m
> Closes #474 splitting jsons

- Functions/xASL_bids_DRO2BIDS.m
- Testing/UnitTests/xASL_ut_UnitTest_function_BIDS2Legacy.m
- Testing/UnitTests/xASL_ut_UnitTest_function_ExploreASL_Master.m
- Testing/UnitTests/xASL_ut_UnitTest_function_Nifti2Im.m
- Testing/xASL_ut_UnitTesting.m
Additional minor unit tests. Check out #527.
> Close #527 Unit Test Update v1.6.0

- ExploreASL_Initialize.m
> Closes #530 ExploreASL_Initialize: Fix population folder bug

- Functions/xASL_adm_DocInitialize.m
> Closes #536 xASL_adm_DocInitialize: Copy additional template

- Functions/xASL_bids_CompareStructures.m
@jan-petr: Can you give this a try and see if it works now?
It doesn't find empty folders right now, so if you know a good regexp that works with these ExploreASL functions then just let me know.
> Closes #535 update bids comparison

- Functions/xASL_num2str.m
> Closes #543 x asl num2str auto mode

- ExploreASL_Import.m
- Modules/SubModule_Import/xASL_imp_DCM2NII.m
This PR should fix the bug mentioned in #545.
Within #514 I revamped the `xASL_imp_DCM2NII_Subject` parameters and forgot to include the same changes in `ExploreASL_Import`.
Would help me a lot if someone could run a small test.
> Closes #545 old import revamp

- Functions/xASL_io_SplitASL.m
Check out #542 (& WhatsApp questions)
> Closes #542 ASL context

- DataParTemplate.m
> Feature #559 make nifti4 dicom

- Functions/xASL_adm_DefineASLSequence.m
> #580 xASL_adm_DefineASLSequence: add GSP ASL-DRO parsing

- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject_ShuffleTheDynamics.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_SubjectSessionRun.m
#591 
Import DEBBIE data of hadamard 4 and 8. Make sure the order in both image and JSON is first TE then PLD.
> #591 multiTE import - taking TE first then PLD

- Functions/xASL_bids_BIDS2Legacy.m
Check out issue #600
Run the import workflow for a flavor and include a TSV file called participants.tsv in the dataset root directory.
None
> #600 xALS_bids_BIDS2Legacy: Copy participants.tsv if it exists

- Functions/xASL_bids_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
Check out #603
Just run the import workflow, you should now get a dataset_description.json within derivatives/ExploreASL
None
> #603 xASL_bids_BIDS2Legacy: Add dataset_description.json

- Functions/xASL_adm_DocInitialize.m
> #615 xASL_adm_DocInitialize: Add CHANGES.md

- Functions/xASL_adm_GetPopulationSessions.m
- Functions/xASL_init_DefineStudyData.m
- Functions/xASL_stat_GetROIstatistics.m
- Functions/xASL_stat_PrintStats.m
> #586 xASL_adm_GetPopulationSessions: avoid crashing if no sessions found

- Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
Closes #620
Needs to be tested in Linux, with a folder with spaces.
> #620 xASL_adm_GzipAllFiles: Allow spaces

- External/bids-matlab/+bids/layout.m
- Functions/xASL_bids_BIDS2Legacy.m
Closes #628
@BeatrizPadrela See description in the issue. If you have sufficiently tested this, feel free to merge after approvals.
> Bug #628 session runs

- Functions/xASL_bids_CompareStructures.m
- Functions/xASL_im_CompareNiftis.m
Check out the detailed explanations in #632
> #632 Compare niftis

- CHANGES.md
> Docu #637 restyle

- ExploreASL_Initialize.m
- Functions/xASL_init_checkDatasetRoot_invalid_starting_2_0.m
- Functions/xASL_vis_CreateVisualFig.m
- Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
#618 
Simple running of the pipeline should be enough to test.
> Bug #618 as land m0check filenames

- Functions/xASL_init_DetermineRequiredPaths.m
- Functions/xASL_init_checkDatasetRoot.m
> Bug #646 load failure

- External/bids-matlab/+bids/layout.m
> Feature #643 bids.layout

- Functions/xASL_im_CreatePseudoCBF.m
- Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
> #649 Move top level paths to x.D

- Functions/xASL_vis_CreateVisualFig.m
> Bug #652 x asl vis create visual fig allow overlay

- ExploreASL_Initialize.m
- Functions/xASL_adm_CleanUpBeforeRerun.m
- Functions/xASL_init_DefinePaths.m
- Functions/xASL_init_FileSystem.m
- Modules/xASL_module_Population.m
> Bug #630 population folder

- ExploreASL_Initialize.m
- Functions/xASL_init_checkDatasetRoot.m
Check out #656
This is the issue that you described in the whatsapp group
> #656 Improve warnings

- Development/StatsAnalysis/ROI_Stats/xASL_stat_Motion.m
- Functions/xASL_Iteration.m
- Functions/xASL_adm_DefineASLSequence.m
- Functions/xASL_init_DefineStudyData.m
- Functions/xASL_init_VisualizationSettings.m
- Functions/xASL_stat_GetROIstatistics.m
- Functions/xASL_stat_PrintStats.m
> Bug #625 session print stats

- Functions/xASL_stat_PrintStats.m
> #659 xASL_stat_PrintStats: Fix visits parsing

- Functions/xASL_adm_GetPopulationSessions.m
#655 
Run Population module for dataset with all subjects the same amount of sessions and subjects with different amount of sessions
> Bug #655 get population sessions warning

- Functions/xASL_init_DetermineRequiredPaths.m
- Functions/xASL_init_checkDatasetRoot_invalid_starting_2_0.m
- Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
#666
Add multiple dataPars or studyPars or sourcestructures and see that a warning is printed with clarifying what file is actually used.
> #666 Warning on multiple DataPar.jsons

- Functions/xASL_bids_parms2BIDS.m
#676 
Test if the warning doesn't appear anymore
> #676 xASL_bids_parms2BIDS Correct position of bReproTesting in x-struct

- Development/xASL_im_Move3DVolume.m
- Modules/SubModule_ASL/xASL_wrp_RealignASL.m
- Modules/xASL_module_ASL.m
> Feature #566 hadamard motion correction

- External/SPMmodified/xASL/xASL_io_Nifti2Im.m
> #187 xASL_io_Nifti2Im: Load as uint8 int16 or single

- External/SPMmodified/xASL/xASL_io_SaveNifti.m
> Feature #595 x asl io save nifti uint8

- ExploreASL_ImportMaster.m
- ExploreASL_Initialize.m
- ExploreASL_Master.m
- Functions/xASL_init_DataLoading.m
- Functions/xASL_init_DefinePaths.m
- Functions/xASL_init_PrintUserFeedback.m
- Functions/xASL_init_RemoveLockDirs.m
- Functions/xASL_init_checkDatasetRoot.m
- Functions/xASL_init_checkDatasetRoot_invalid_starting_2_0.m
> #683 Revamp data loading

- Functions/xASL_init_checkDatasetRoot.m
> #707 xASL_init_checkDatasetRoot: minor fix derivatives path check

- External/README_SPM.txt
> #714 cat_wmh_miccai2017: minor cleanup lower slices

- Functions/xASL_fsl_TopUp.m
> #692 xASL_fsl_TopUp: Reused variable corrected

- Development/StatsAnalysis/SPM_VBA_Stats/xASL_spm_GLM.m
- Development/StatsAnalysis/SPM_VBA_Stats/xASL_wrp_spm_GLM.m
- External/SPMmodified/xASL/xASL_adm_GetFileList.m
- External/SPMmodified/xASL/xASL_im_LesionRemoval4CAT.m
- External/SPMmodified/xASL/xASL_im_SaveOriginal4CAT.m
- Functions/xASL_adm_CleanUpBeforeRerun.m
- Functions/xASL_adm_CompareDataSets.m
- Functions/xASL_adm_CreateFileReport.m
- Functions/xASL_adm_LesionResliceList.m
- Functions/xASL_im_Lesion2CAT.m
- Modules/SubModule_Population/xASL_adm_DeleteManyTempFiles.m
- Modules/SubModule_Population/xASL_qc_SortBySpatialCoV.m
- Modules/SubModule_Population/xASL_stat_ComputeWsCV.m
- Modules/SubModule_Population/xASL_stat_GetVolumeStatistics.m
- Modules/SubModule_Population/xASL_wrp_CreateBiasfield.m
- Modules/SubModule_Structural/xASL_wrp_LST_Segment_FLAIR_WMH.m
- Modules/SubModule_Structural/xASL_wrp_LinearReg_FLAIR2T1w.m
- Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m
- Modules/SubModule_Structural/xASL_wrp_SegmentT1w.m
- Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
- Modules/xASL_module_ASL.m
- Modules/xASL_module_DARTEL.m
- Modules/xASL_module_Import.m
- Modules/xASL_module_LongReg.m
- Modules/xASL_module_Population.m
- Modules/xASL_module_Structural.m
- Testing/xASL_qc_TestExploreASL.m
> Opt #412 x asl adm get file list case insensitive reg exp

- Functions/xASL_adm_GetPopulationSessions.m
- Functions/xASL_stat_PrintStats.m
> Bug #725 incorrect printing cbf statistics

- DataParTemplate.m
- Functions/xASL_fsl_TopUp.m
- Functions/xASL_vis_CreateVisualFig.m
- Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
#721
I have tested 10 TestDataSets and all runs good. Plus for the first, I have tested contours and contours from template and the QC in ASLcheck also looks good.
> Optimize #721 contour fix

- External/SPMmodified/xASL/xASL_adm_DeleteFileList.m
- Functions/xASL_quant_Basil.m
- Testing/UnitTests/xASL_ut_function_xASL_adm_DeleteFileList.m
Closes #565
Please check the issue, thanks!
> Bug #565 xASL_adm_DeleteFileList symlink

- ExploreASL_ProcessMaster.m
- Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
- Modules/xASL_module_Population.m
Check out description in #696.
I tested it by rerunning the population module of a few datasets. Will run the single test dataset now, too.
Check out our discussion in #696.
> #696 Move xASL_adm_GzipAllFiles to ExploreASL_ProcessMaster

- Modules/SubModule_ASL/xASL_wrp_VisualQC_ASL.m
> #754 xASL_wrp_VisualQC_ASL: correct input xASL_qc_PrintOrientation

- Functions/xASL_init_checkDatasetRoot.m
#758
@BeatrizPadrela & @HenkMutsaerts: would be cool if you would test this to validate that it's working correctly.
> Fixes #758 bug in data loading

- Modules/xASL_module_ASL.m
#761
@BeatrizPadrela & @HenkMutsaerts: would be cool if you would test this to validate that it's working correctly.
> Fixes #761 xASL_module_ASL: Minor fix for empty images

- Functions/xASL_im_DetermineFlip.m
> #757 xASL_im_DetermineFlip: Fix bug introduced by merging

- ExploreASL_Initialize.m
> Fixes #769 Load data bug

- Functions/xASL_qc_CollectQC_Structural.m
> #770 change struct variable name

- Functions/xASL_stat_PrintStats.m
> #731 sCoV stats file prints mL/100g/min

- Modules/SubModule_Population/xASL_wrp_CreateBiasfield.m
#257
@MauricePasternak sorry for the delay, this should fix your issue. @Mathijs you can test this with NOMARED, if you call the different sequences "sites" (we may want to rename this later).
> Fixes #257 xASL_wrp_CreateBiasfield: Slight revamp

- External/SPMmodified/xASL/xASL_Move.m
#774
Basic testing done. Beatriz will check on OASIS
> Bug #774 move identical files

- Modules/SubModule_Population/xASL_stat_GetDICOMStatistics.m
#762
@BeatrizPadrela & @HenkMutsaerts: would be cool if you would test this to validate that it's working correctly.
> Fixes #762 xASL_stat_GetDICOMStatistics: Improve TSV cell array fixing

- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject_DefineM0Type.m
#784 
To make the import of ADNI Philips work
> Bug #784 m0 type bid simport

- Functions/xASL_bids_CheckDatasetDescription.m
- Functions/xASL_bids_CompareStructures.m
- Functions/xASL_bids_CreateDatasetDescriptionTemplate.m
- Functions/xASL_im_CompareNiftis.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS.m
- Modules/xASL_module_Import.m
- Testing/UnitTests/xASL_ut_function_xASL_bids_CheckDatasetDescription.m
> Fixes #746 Record ExploreASL version on Import

- Functions/xASL_test_Flavors_DCM2BIDS.m
#178 
Simply fix only that renames a few datasets - can be quickly approved. The main work was done in the Flavors repository.
>  #178 xASL_test_Flavors_DSM2BIDS: Updated new flavors names

- ExploreASL_ImportMaster.m
- ExploreASL_Master.m
- ExploreASL_ProcessMaster.m
- Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
- Testing/UnitTests/xASL_ut_master_xASL_ExploreASL_Master.m
> Fixes #787 Move bImportData & bProcessData

- Functions/xASL_bids_CompareStructures.m
- Functions/xASL_bids_MergeNifti.m
- Functions/xASL_bids_MergeNifti_SeriesNumber.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject_ShuffleTheDynamics.m
> #790 Merge ASL files in import by SeriesNumber

- Modules/SubModule_Import/xASL_imp_DCM2NII.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject_ShuffleTheDynamics.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Run.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunAnat.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunPerf.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m
- Modules/SubModule_Population/xASL_stat_GetDICOMStatistics.m
> Bug #796 bugfixing

- Functions/xASL_bids_Dicom2JSON.m
Closes #806
@jan-petr Perhaps you also want to fix this in an earlier stage, but I would still leave this check in place; it shouldn't hurt.
> #806 xASL_bids_Dicom2JSON: Fix multiple identical values

- Modules/SubModule_Import/xASL_imp_NII2BIDS.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Run.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunAnat.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Session.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m
- Modules/xASL_module_Import.m
> #808 xASL_imp_NII2BIDS_Run: catch errors

- External/bids-matlab/+bids/layout.m
- Modules/SubModule_Import/xASL_imp_Initialize.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Run.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunAnat.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunPerf.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Session.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m
> #810 bids.layout: Fix session name extraction

- CHANGES.md
- Functions/xASL_fsl_RunFSL.m
- Functions/xASL_quant_Basil.m
- Functions/xASL_quant_SinglePLD.m
#818
https://github.com/ExploreASL/ExploreASL/pull/816#issuecomment-915274543
> Closes #818 Use output parameter to prevent pipeline crashes

- Functions/xASL_adm_Dicom2Parms.m
- Functions/xASL_bids_Dicom2JSON.m
> #801 xASL_*_Dicom2(Parms|JSON): Avoid reporting defaults missing

- External/SPMmodified/xASL/xASL_system.m
- Testing/xASL_qc_TestExploreASL.m
Closes #845 (partly)
See header of `xASL_system`. We should be able to merge this now, and improve this function later (according to #845), so then the other Wishlist contents from #845 can then be moved to a new issue :)
> Feature #845 x asl system

- Functions/xASL_bids_BIDSifyCheckTimeEncoded.m
- Functions/xASL_im_HadamardDecoding.m
- Functions/xASL_quant_HadamardDecoding.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
- Modules/xASL_module_ASL.m
Required: mention the issue number of the linked feature or bug here
> Feature #640 hadamard decoding

- Functions/xASL_stat_GetROIstatistics.m
- Modules/SubModule_ASL/xASL_wrp_CreateAnalysisMask.m
- Modules/SubModule_ASL/xASL_wrp_Quantify.m
- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
- Modules/xASL_module_Population.m
> Fixes #827 xASL_module_Population: avoid running parallelized

- Functions/xASL_bids_BIDSifyAnatJSON.m
Check out #848
@BeatrizPadrela: please test this with the twins data
> Fixes #848 xASL_bids_BIDSifyAnatJSON: check parameter size, raise warning

- External/SPMmodified/xASL/xASL_spm_admin.m
- Testing/UnitTests/xASL_ut_function_xASL_spm_admin.m
- Testing/UnitTests/xASL_ut_function_xASL_spm_reslice.m
- Testing/UnitTests/xASL_ut_function_xASL_spm_smooth.m
Check out #855
Run these tests:
```matlab
TestRepository = '...';
UnitTest1 = xASL_ut_function_xASL_spm_reslice(TestRepository);
UnitTest2 = xASL_ut_function_xASL_spm_smooth(TestRepository);
UnitTest3 = xASL_ut_function_xASL_spm_admin(TestRepository);
```
@jan-petr: This is just a starting point for us to get some unit tests for the actual image processing. No over-engineering here. Let's start simple. No special requests, please.
> Fixes #855 SPM unit tests

- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunAnat.m
> Fixes #860 xASL_imp_DCM2NII & NII2BIDS: fix behavior for multiple anat files

- ExploreASL_Initialize.m
- Testing/xASL_test_UnitTesting.m
Check out #864
Just a super minor change. Probably doesn't need testing at all.
> Fixes #864 Improve user feedback (testing and initialization)

- Functions/xASL_init_LongitudinalRegistration.m
- Modules/xASL_module_LongReg.m
> Fixes #853 longitudinal registration

- Functions/xASL_adm_DefineASLSequence.m
- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
Check out #868
We tested using the twins dataset
> Fixes #868 xASL_im_CreateAnalysisMask: defaults

- External/fsl/b02b0.cnf
- Functions/xASL_fsl_TopUp.m
> Closes Bug #891 fsl top up configuration

- Functions/xASL_im_M0ErodeSmoothExtrapolate.m
> Closes #909 xASL_im_M0ErodeSmoothExtrapolate: lower threshold fixed

- ExploreASL_Initialize.m
> Closes #892 ExploreASL_Initialize: rm paths before addpath

- Functions/xASL_fsl_SetFSLdir.m
> Closes #907 xASL_fsl_SetFSLdir: add WSL2 compatibility

- Modules/xASL_module_ASL.m
> Closes #911 xASL_module_ASL: Revamp initialization

- Modules/SubModule_ASL/xASL_wrp_Quantify.m
> #925 Fix default T1 and LabEff for 7T

- Functions/xASL_qc_CollectQC_ASL.m
- Functions/xASL_quant_BSupCalculation.m
- Functions/xASL_quant_Basil.m
- Functions/xASL_quant_MultiPLD.m
- Modules/SubModule_ASL/xASL_wrp_Quantify.m
- Modules/SubModule_ASL/xASL_wrp_RealignASL.m
- Modules/SubModule_ASL/xASL_wrp_RegisterASL.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
- Modules/xASL_module_ASL.m
> Fixes #759 Adapting xASL to multi-PLD

- Functions/xASL_Iteration.m
- Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_CreateSummaryFile.m
- Modules/SubModule_Import/xASL_imp_FinishImport.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_RunPerf.m
> #930 xASL_Iteration: move logs

- Functions/xASL_adm_CorrectName.m
- Modules/SubModule_Import/xASL_imp_BasicParameterChecks.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject.m
- Modules/SubModule_Import/xASL_imp_Initialize.m
Check out #923
Run the flavors import.
> Closes #923 Subject ID format

- Functions/xASL_io_dcm2nii.m
- Modules/SubModule_Import/xASL_imp_CheckImportSettings.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m
- Modules/SubModule_Import/xASL_imp_TokenBackwardsCompatibility.m
> Closes Bug #938 redundant dcm2nii behavior

- Modules/SubModule_Import/xASL_imp_DetermineSubjectStructure.m
- Modules/SubModule_Import/xASL_imp_ReadSourceData.m
> Closes #929 Improved warning

- Functions/xASL_init_DetermineRequiredPaths.m
- Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_ConvertScan.m
- Modules/SubModule_Import/xASL_imp_FinishImport.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m
> Closes #936 Check directories for reruns/crashed imports

- Functions/xASL_Iteration.m
- Functions/xASL_init_LongitudinalRegistration.m
- Modules/SubModule_Import/xASL_bids_BIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_NII2BIDS_Subject.m
> Closes #945 Bugfix

- Modules/SubModule_Import/xASL_imp_DCM2NII.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_Subject.m
- Modules/SubModule_Import/xASL_imp_DetermineSubjectStructure.m
- Modules/SubModule_Import/xASL_imp_ImportInitialization.m
- Modules/xASL_module_Import.m
Check out the description in #948
Seems like we overlooked this minor bug in the previous merge.
> Closes #948 Update x.SUBJECT/S and x.overview

- Functions/xASL_im_CompareNiftis.m
- Testing/UnitTests/xASL_ut_function_xASL_im_CompareNiftis.m
Check out #712
Does this work for you?
> Closes #712 Data type comparison

- Modules/SubModule_ASL/xASL_wrp_PVC.m
> #956 xASL_wrp_PVC: Convert kernel size to row vector

- ExploreASL_ImportMaster.m
- Modules/SubModule_Import/xASL_imp_CompleteBIDS2Legacy.m
- Modules/SubModule_Import/xASL_imp_FinishImport.m
> Closes #947 Update finish import script

- Modules/SubModule_Structural/xASL_wrp_LinearReg_T1w2MNI.m
> Closes #873 Avoid double ASL4D registration

- Development/StatsAnalysis/StatTestCompare/StatTrial.m
- Functions/xASL_Iteration.m
> Optimize #902 remove parfor

- Functions/xASL_quant_GetControlLabelOrder.m
- Functions/xASL_quant_GetMeanControl.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
Should work alreayd for Hadamard and for the other data formats
> Optimize #971 get mean control

- Functions/xASL_quant_HadamardDecoding.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
- Modules/xASL_module_ASL.m
> Feature #963 hadamard decoding philips

- Functions/xASL_bids_BIDSifyASLJSON.m
> Closes #975 Fix GE eASL import

- Functions/xASL_bids_parseM0.m
- Functions/xASL_io_SplitASL.m
> Bug #980 fix m0 split

- .github/ISSUE_TEMPLATE/template_bug.md
- .github/ISSUE_TEMPLATE/template_feature.md
Check out #993
No testing required.
Just a minor template check.
> Closes #993 Update GitHub templates

- ExploreASL_ImportMaster.m
- Modules/xASL_module_Import.m
Check out #979
Run `x = ExploreASL(pathHadamardDataset, [1 1 0 1], 1);`
@jan-petr: Does it work like that on your end?
> Closes #979 Import & Processing don't run together (Hadamard)

- Functions/xASL_bids_parms2BIDS.m
- Functions/xASL_init_FileSystem.m
- Functions/xASL_io_SplitASL.m
- Functions/xASL_quant_Basil.m
- Functions/xASL_quant_GetMeanControl.m
- Functions/xASL_quant_MultiPLD.m
- Functions/xASL_quant_SinglePLD.m
- Modules/SubModule_ASL/xASL_wrp_Quantify.m
- Modules/SubModule_ASL/xASL_wrp_RealignASL.m
- Modules/SubModule_ASL/xASL_wrp_ResampleASL.m
- Modules/xASL_module_ASL.m
- Testing/UnitTests/xASL_ut_function_xASL_bids_BIDS2Legacy.m
- Testing/UnitTests/xASL_ut_master_xASL_ExploreASL_Master.m
> Closes #978 Multi PLD quantification

- CHANGES.md
- External/SPMmodified/xASL/xASL_im_FillNaNs.m
- Functions/xASL_im_CreateASLDeformationField.m
- Functions/xASL_im_M0ErodeSmoothExtrapolate.m
- Modules/SubModule_ASL/xASL_wrp_ProcessM0.m
- Modules/SubModule_Structural/xASL_wrp_SegmentT1w.m
- Modules/xASL_module_DARTEL.m
- Modules/xASL_module_LongReg.m
> Bug #1033 m0 masking

- ExploreASL_Initialize.m
- Functions/xASL_num2str.m
- Functions/xASL_quant_BSupCalculation.m
- Functions/xASL_quant_M0.m
- Functions/xASL_quant_MultiPLD.m
- Functions/xASL_quant_SinglePLD.m
- Testing/UnitTests/xASL_ut_function_xASL_num2str.m
Check out #995. Did some minor changes to the original idea. Someone still has to go through the pipeline and check for potential problems.
> Closes #995 num2str changes

- Modules/SubModule_ASL/xASL_wrp_Quantify.m
> #1055 Checks for unique values of ASL TEs

- Modules/SubModule_ASL/xASL_wrp_Quantify.m
#1046 
The quantification of multi-TE Hadamard still doesn't work as we need the new BASIL version, but at least it calculates PWI and doesn't crash before.
> Closes #1046 Fix M0 with multi-TE

- Modules/SubModule_Population/xASL_im_CreateAnalysisMask.m
#1068 
An error we had there for a long time, incurred during a revamp. And since there were two errors, they canceled themselves out, completely putting this function out of work. Thanks to the Japanese group who have noticed that!
It should all be fine - but please see if it makes sense to you.
> Closes #1068 Fix create analysis mask

- Functions/BIDS/xASL_bids_BIDSifyASLJSON.m
- Functions/BIDS/xASL_bids_BIDSifyCheckTimeEncoded.m
- Modules/SubModule_Import/xASL_imp_DCM2NII_ReorderTimeEncoded.m
- Modules/SubModule_Population/xASL_stat_GetDICOMStatistics.m
#1059 
I ran the Hadamard datasets...
...and all of the issues are solved. Import done correctly  👍
> Closes #1059 hadamard import corrections

- ExploreASL_Initialize.m
- Functions/Import/xASL_imp_DCM2NII_Subject_StartConversion.m
- Functions/InputOutput/xASL_io_dcm2nii.m
- Testing/xASL_test_TestExploreASL.m
> Bug #1105 revert add optional

- Functions/ImageProcessing/xASL_im_Lesion2Mask.m
- Functions/ImageProcessing/xASL_im_M0ErodeSmoothExtrapolate.m
- Functions/Initialization/xASL_init_FileSystem.m
- Functions/Quantification/xASL_quant_FEAST.m
- Functions/Statistics/xASL_stat_PrintStats.m
- Functions/Visualization/xASL_vis_Imwrite.m
- Functions/Visualization/xASL_vis_OverlapT1_ASL.m
- Functions/Visualization/xASL_vis_VisualizeROIs.m
- Modules/SubModule_ASL/xASL_wrp_RealignASL.m
- Modules/SubModule_Population/xASL_stat_ComputeWsCV.m
- Modules/SubModule_Population/xASL_stat_GetAcquisitionTime.m
- Modules/SubModule_Population/xASL_stat_GetDICOMStatistics.m
- Modules/SubModule_Population/xASL_stat_GetMotionStatistics.m
- Modules/SubModule_Structural/xASL_wrp_GetVolumetrics.m
- Modules/SubModule_Structural/xASL_wrp_VisualQC_Structural.m
- Modules/xASL_module_Population.m
Closes #390
@HenkMutsaerts 
Run `xASL_qc_TestExploreASL` (after Jan has reverted this one from `xASL_test_ExploreASL` ;)
@jan-petr 
Tested with `xASL_qc_TestExploreASL` on AMCs Flux Redhat server:
ResultsTable =
11×11 cell array
Columns 1 through 4
{'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tot…'}    {'median_qCBF_Dee…'}
{'GE_3Dspiral_T1p…'}    {'65.2179'          }    {'52.5863'          }    {'32.228'           }
{'Philips_2DEPI_F…'}    {'39.044'           }    {'27.6548'          }    {'6.6907'           }
{'Philips_2DEPI_F…'}    {'74.0847'          }    {'56.3353'          }    {'22.9927'          }
{'Philips_2DEPI_F…'}    {'48.8251'          }    {'43.3459'          }    {'20.2235'          }
{'Philips_2DEPI_L…'}    {'empty'            }    {'14.182'           } …
> Closes #390 check dir behavior

- Functions/Quantification/xASL_quant_Hct2BloodT1.m
> #1112 Fix comments in hematocrit correction

- Modules/SubModule_ASL/xASL_wrp_PVC.m
> #844 xASL_wrp_PVC transform CBFgm to MNI

- Functions/Initialization/xASL_init_DefineStudyData.m
> Closes #1123 xASL_init_DefineStudyData: Avoid loading log as subject

- Functions/Initialization/xASL_init_DefineIndependentSettings.m
> Closes #1134 xASL_init_DefineIndependentSettings

- Functions/Initialization/xASL_init_checkDatasetRoot.m
> Closes #1142 xASL_init_checkDataSetRoot

- Functions/Initialization/xASL_init_checkDatasetRoot.m
> #1153 xASL_init_checkDatasetRoot fix

- ExploreASL_Import.m
- ExploreASL_Initialize.m
- ExploreASL_Process.m
- Functions/Initialization/xASL_init_DataLoading.m
Close #1115 
I have tested it previously and fixed all bugs. And there are no conflicts. So can be immediately merged. Check also my comments at the end of the issue.
> Opt #1115 separate import processing

- Modules/xASL_module_BIDS2Legacy.m
> #1155 Fix path update before BIDS2Legacy

- Functions/Statistics/xASL_stat_PrintStats.m
- Modules/SubModule_Population/xASL_qc_SortBySpatialCoV.m
- Modules/SubModule_Population/xASL_stat_GetRegistrationStatistics.m
- Modules/xASL_module_Population.m
> Closes #1117 population module mathijs

- Modules/SubModule_Population/xASL_adm_GzipAllFiles.m
> Closes #1164 x asl adm gzip all files

- Functions/Import/xASL_imp_NII2BIDS_RunAnat.m
- Functions/Import/xASL_imp_NII2BIDS_RunPerf.m
- Functions/InputOutput/xASL_io_dcm2nii.m
> Bug #1167 nii2 bids new

- Functions/Initialization/xASL_init_FileSystem.m
> Bug #1182 atlas names

- External/SPMmodified/xASL/xASL_csvRead.m
- External/SPMmodified/xASL/xASL_csvWrite.m
> #1187 changed PathTSV to PathCSV

- Functions/Import/xASL_imp_DCM2NII_SanityChecks.m
- Functions/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m
- Functions/Import/xASL_imp_DetermineStructureFromSourcedata.m
- Functions/Import/xASL_imp_DetermineSubjectStructure.m
- Functions/Import/xASL_imp_PreallocateGlobalCounts.m
- Functions/Import/xASL_imp_StudyParPriority.m
- Functions/Initialization/xASL_init_LoadDataParameterFile.m
- Functions/InputOutput/xASL_io_ReadDataPar.m
- Modules/SubModule_Import/xASL_wrp_DCM2NII.m
- Modules/SubModule_Import/xASL_wrp_DCM2NII_Subject.m
- Modules/SubModule_Import/xASL_wrp_NII2BIDS.m
- Modules/SubModule_Import/xASL_wrp_NII2BIDS_Subject.m
- Testing/UnitTests/xASL_ut_function_xASL_imp_StudyParPriority.m
Closes #1129
Check flavor /Siemens_PCASL_3DGRASE_VD13A_DEBBIE_1 and Siemens_PCASL_multi_VE11C_1
> Feature #1129 multi study context

- Functions/BIDS/xASL_bids_BIDSifyCheckTimeEncoded.m
- Functions/BIDS/xASL_bids_MergeNifti.m
- Functions/Import/xASL_imp_CheckIfFME.m
- Functions/Import/xASL_imp_DCM2NII_CheckIfFME.m
- Functions/Import/xASL_imp_DCM2NII_ReorderTimeEncoded.m
- Functions/Import/xASL_imp_DCM2NII_Subject_SortASLVolumes.m
> #1218 xASL_bids_MergeNifti Fix TE ordering

- Functions/Import/xASL_imp_DetermineStructureFromSourcedata.m
- Functions/Import/xASL_imp_ReadSourceData.m
> #1242 Report empty tokenOrdering

- README.md
> #1222 Update links in README

- Functions/Quantification/xASL_quant_M0.m
> Bug #1124 b sup m0 correction multi pld

- CHANGES.md
- Testing/xASL_test_Flavors.m
> Closes #1262 xASL_test_Flavors

- CHANGES.md
- Functions/InputOutput/xASL_io_dcm2nii.m
- Testing/xASL_test_Flavors.m
> Close #1271
